// SIGNUP
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_FETCH_SUCCEEDED = "SIGNUP_FETCH_SUCCEEDED";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

// SIGNIN
export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_FETCH_SUCCEEDED = "SIGNIN_FETCH_SUCCEEDED";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

// REFRESH
export const REFRESH_START = "REFRESH_START";
export const REFRESH_SUCCEED = "REFRESH_SUCCEED";
export const REFRESH_FAILED = "REFRESH_FAILED";

// LOGOUT
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCEED = "LOGOUT_SUCCEED";

// ERRORS
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// CHECK
export const CHECK_USER = "CHECK_USER";

// GETINFO
export const GETINFO_START = "GETINFO_START";
export const GETINFO_FETCH_SUCCEEDED = "GETINFO_FETCH_SUCCEEDED";
export const GETINFO_FAILED = "GETINFO_FAILED";

// GETTRANSHIS
export const GET_TRANS_HISTORY = "GET_TRANS_HISTORY";
export const GET_TRANS_HISTORY_SUCCEEDED = "GET_TRANS_HISTORY_SUCCEEDED";

// STOCK_LIST
export const GET_STOCK_LIST = "GET_STOCK_LIST";
export const GET_STOCK_LIST_SUCCEED = "GET_STOCK_LIST_SUCCEED";

// BUY_STOCK
export const BUYING_STOCK = "BUYING_STOCK";
export const BOUGHT_STOCK = "BOUGHT_STOCK";
export const BUYING_STOCK_FAILED = "BUYING_STOCK_FAILED";

// SELL_STOCK
export const SELLING_STOCK = "SELLING_STOCK";
export const SOLD_STOCK = "SOLD_STOCK";
export const SELLING_STOCK_FAILED = "BUYING_STOCK_FAILED";

// CHART
export const GOT_STOCK_HISTORY_START = "GOT_STOCK_HISTORY_START";
export const GOT_STOCK_HISTORY = "GOT_STOCK_HISTORY";
